name: ${project.name}
author: TrueMB
version: ${project.version}
api-version: 1.16
main: me.truemb.soundmuffler.main.Main
depend: [ProtocolLib]

commands:
     soundmuffler:
         description: Sound Muffler Command
         aliases: [sm]